/**
 * backendApi.ts — Adaptador unificado para los 3 backends .NET
 *
 * ┌──────────────────────────────────────────────────────────────────┐
 * │  BACKEND                 PORT    MÓDULOS (DDL Oracle)             │
 * ├──────────────────────────────────────────────────────────────────┤
 * │  aeropuerto_be-develop   :5087   Módulos 1,2,3,4,5,6,21-29      │
 * │                                  aeropuertos, aerolineas,        │
 * │                                  vuelos, programas_vuelo,        │
 * │                                  tripulacion, meteorología        │
 * │  aeropuerto_be-Gerson    :5088   Módulos 7,8,9,10,11,12,13,14   │
 * │                                  pasajeros, reservas, hoteles,   │
 * │                                  checkin, seguridad, comercial,  │
 * │                                  lealtad, promociones, transporte│
 * │  aeropuerto_be-modulos   :5089   Módulos 15,16,17,18,19,20      │
 * │                                  empleados, finanzas, carga,     │
 * │                                  menores, mantenimiento           │
 * └──────────────────────────────────────────────────────────────────┘
 *
 * ✅ Tipos alineados al DDL Oracle (GENERATED BY DEFAULT AS IDENTITY)
 * ✅ Todos los endpoints PascalCase (ASP.NET JsonNamingPolicy = null)
 */

// ─── Base URLs ────────────────────────────────────────────────────────────────
// ✅ Todos los módulos están unificados en aeropuerto_be-develop (:5087)
const BE_UNIFIED = process.env.EXPO_PUBLIC_BE_URL ?? 'http://localhost:5087';
const BE_DEVELOP = BE_UNIFIED;
const BE_GERSON  = BE_UNIFIED;   // Ya no es un backend separado
const BE_MODULOS = BE_UNIFIED;   // Ya no es un backend separado

const TIMEOUT_MS = 8000;

// ─── Generic fetch with timeout & auth header ─────────────────────────────────
async function req<T>(base: string, path: string, opts?: RequestInit): Promise<T> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${base}${path}`, {
      ...opts,
      signal: ctrl.signal,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        ...opts?.headers,
      },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
    return res.json() as Promise<T>;
  } catch (e: any) {
    if (e.name === 'AbortError') throw new Error(`TIMEOUT: ${base}${path}`);
    throw e;
  } finally {
    clearTimeout(timer);
  }
}

const get  = <T>(base: string, path: string) => req<T>(base, path);
const post = <T>(base: string, path: string, body: unknown) =>
  req<T>(base, path, { method: 'POST', body: JSON.stringify(body) });
const put  = <T>(base: string, path: string, body: unknown) =>
  req<T>(base, path, { method: 'PUT',  body: JSON.stringify(body) });
const del  = (base: string, path: string) =>
  req<void>(base, path, { method: 'DELETE' });

// ═══════════════════════════════════════════════════════════════════════════════
// TIPOS — Mapeados 1:1 con las columnas del DDL Oracle
// ═══════════════════════════════════════════════════════════════════════════════

// ── MÓDULO 1: INFRAESTRUCTURA AEROPORTUARIA ───────────────────────────────────

/** DDL: aeropuertos (codigo_aeropuerto PK natural) */
export interface BE_Aeropuerto {
  CodigoAeropuerto: string;
  Nombre:           string;
  Ciudad:           string;
  Pais:             string;
  Region?:          string;
  Continente?:      string;
  HusoHorario?:     string;
  Latitud?:         number;
  Longitud?:        number;
  ElevacionMetros?: number;
  Terminales?:      number;
  PuertasAbordaje?: number;
  Activo:           number;        // NUMBER(1) DEFAULT 1
  FechaRegistro?:   string;
}

/** DDL: puertas_embarque */
export interface BE_PuertaEmbarque {
  IdPuerta:         number;
  CodigoAeropuerto: string;
  NumeroPuerta:     string;
  Terminal:         string;
  TipoPuerta?:      string;        // NACIONAL | INTERNACIONAL | MIXTA
  CapacidadMaxima?: number;
  TienePasarela?:   number;
  Activo:           number;
}

/** DDL: pistas_aterrizaje */
export interface BE_Pista {
  IdPista:              number;
  CodigoAeropuerto:     string;
  NumeroPista:          string;
  LongitudMetros?:      number;
  SuperficieS?:          string;
  IluminacionNocturna?: number;
  SistemaIls?:          number;
  Activo:               number;
}

// ── MÓDULO 2: FLOTA AÉREA ────────────────────────────────────────────────────

/** DDL: modelos_aviones */
export interface BE_ModeloAvion {
  IdModelo:               number;
  NombreModelo:           string;
  Fabricante?:            string;
  CapacidadPasajeros:     number;
  CapacidadCargaKg?:      number;
  AutonomiakM?:           number;
  VelocidadCruceroKmh?:   number;
  TripulacionMinima?:     number;
  Activo:                 number;
}

/** DDL: mantenimiento_aviones */
export interface BE_MantenimientoAvion {
  IdMantenimiento:       number;
  MatriculaAvion?:       string;
  IdModelo?:             number;
  FechaMantenimiento?:   string;
  TipoMantenimiento?:    string;   // PREVENTIVO | CORRECTIVO | PREDICTIVO | MAYOR
  Descripcion?:          string;
  HorasVueloActuales?:   number;
  ProximoMantenimiento?: string;
  Costo?:                number;
  TallerS?:               string;
  TecnicoResponsable?:   string;
}

// ── MÓDULO 3: AEROLÍNEAS ─────────────────────────────────────────────────────

/** DDL: aerolineas */
export interface BE_Aerolinea {
  IdAerolinea:       number;
  NombreAerolinea:   string;
  CodigoIata?:       string;
  CodigoOaci?:       string;
  PaisOrigen?:       string;
  AnioFundacion?:    number;
  FlotaTotal?:       number;
  DestinosTotales?:  number;
  Alianza?:          string;       // STAR_ALLIANCE | SKYTEAM | ONEWORLD | NINGUNA
  Website?:          string;
  TelefonoContacto?: string;
  EmailContacto?:    string;
  Activo:            number;
  FechaRegistro?:    string;
}

/** DDL: tipos_aerolinea */
export interface BE_TipoAerolinea {
  IdTipoAerolinea: number;
  Descripcion:     string;         // COMERCIAL | CARGA | CHARTER | EJECUTIVA | LOW_COST
  Activo:          number;
}

/** DDL: franquicias_equipaje */
export interface BE_FranquiciaEquipaje {
  IdFranquicia:          number;
  IdAerolinea:           number;
  ClaseServicio?:        string;
  PesoMaximoKg?:         number;
  PiezasPermitidas?:     number;
  DimensionesMaximasCm?: string;
  ExcesoEquipajeCosto?:  number;
  Moneda?:               string;
}

// ── MÓDULO 4: PROGRAMACIÓN DE VUELOS ─────────────────────────────────────────

/** DDL: programas_vuelo */
export interface BE_ProgramaVuelo {
  IdPrograma:                  number;
  NumeroVuelo:                 string;
  IdAerolinea:                 number;
  AeropuertoOrigen:            string;
  AeropuertoDestino:           string;
  TipoVuelo?:                  string;   // NACIONAL | INTERNACIONAL
  DuracionEstimadaMinutos?:    number;
  DistanciaKm?:                number;
  ClaseServicio?:              string;   // ECONOMICA | EJECUTIVA | PRIMERA_CLASE | MIXTA
  Activo:                      number;
  FechaInicio?:                string;
  FechaFin?:                   string;
}

/** DDL: temporadas_vuelo */
export interface BE_TemporadaVuelo {
  IdTemporada:      number;
  NombreTemporada?: string;
  FechaInicio?:     string;
  FechaFin?:        string;
  FactorDemanda?:   number;   // 0.5 – 2.0
  Activa:           number;
}

// ── MÓDULO 5: OPERACIONES DE VUELO ───────────────────────────────────────────

/** DDL: vuelos
 *  Tabla central de operaciones — referenciada por casi todos los módulos
 */
export interface BE_Vuelo {
  IdVuelo:                number;
  IdPrograma:             number;
  FechaVuelo?:            string;
  HoraSalidaProgramada?:  string;
  HoraLlegadaProgramada?: string;
  HoraSalidaReal?:        string;
  HoraLlegadaReal?:       string;
  IdModeloAvion:          number;
  MatriculaAvion?:        string;
  PlazasVacias?:          number;
  PlazasOcupadas?:        number;
  CargaKg?:               number;
  CombustibleLitros?:     number;
  EstadoVuelo?:           string;  // PROGRAMADO|EN_VUELO|ATERRIZADO|CANCELADO|…
  MotivoCancelacion?:     string;
  IdPuertaSalida?:        number;
  IdPuertaLlegada?:       number;
  ObservacionesOperativas?: string;
  // Derived from JOIN with programas_vuelo (some APIs include these)
  NumeroVuelo?:           string;
  AeropuertoOrigen?:      string;
  AeropuertoDestino?:     string;
  NombreAerolinea?:       string;
  CodigoIata?:            string;
  DuracionMinutos?:       number;
}

/** DDL: condiciones_meteorologicas */
export interface BE_Meteorologia {
  IdCondicion:           number;
  CodigoAeropuerto:      string;
  FechaHora?:            string;
  Temperatura?:          number;
  Humedad?:              number;
  PresionAtmosferica?:   number;
  VientoVelocidad?:      number;
  VientosDireccion?:     string;
  VisibilidadKm?:        number;
  CondicionGeneral?:     string;
  FenomenosEspeciales?:  string;
}

/** DDL: incidentes_vuelo */
export interface BE_IncidenteVuelo {
  IdIncidenteVuelo: number;
  IdVuelo:          number;
  FechaIncidente?:  string;
  TipoIncidente?:   string;  // TECNICO | MEDICO | SEGURIDAD | CLIMATICO | OPERATIVO
  Descripcion?:     string;
  Gravedad?:        string;  // BAJA | MEDIA | ALTA | CRITICA
  AccionesTomadas?: string;
  ReportadoPor?:    string;
}

/** DDL: retrasos_vuelo */
export interface BE_RetrasoVuelo {
  IdRetraso:              number;
  IdVuelo:                number;
  MinutosRetraso?:        number;
  TipoRetraso?:           string;  // CLIMATICO | TECNICO | OPERACIONAL | …
  Causa?:                 string;
  Responsable?:           string;
  CompensacionPasajeros?: number;
}

// ── MÓDULO 6: TRIPULACIÓN ─────────────────────────────────────────────────────

/** DDL: tripulacion */
export interface BE_Tripulante {
  IdTripulante:             number;
  Nombres?:                 string;
  Apellidos?:               string;
  TipoDocumento?:           string;
  NumeroDocumento?:         string;
  FechaNacimiento?:         string;
  Nacionalidad?:            string;
  TipoTripulante?:          string; // PILOTO | COPILOTO | SOBRECARGO | INGENIERO | AUXILIAR
  Licencia?:                string;
  FechaLicencia?:           string;
  FechaVencimientoLicencia?: string;
  HorasVueloAcumuladas?:    number;
  Activo:                   number;
}

// ── MÓDULO 7: PASAJEROS ──────────────────────────────────────────────────────

/** DDL: pasajeros */
export interface BE_Pasajero {
  IdPasajero:        number;
  Nombres:           string;
  Apellidos:          string;
  TipoDocumento?:    string;  // DPI | PASAPORTE | OTRO
  NumeroDocumento:   string;
  Nacionalidad?:     string;
  FechaNacimiento?:  string;
  Genero?:           string;  // M | F | O
  Telefono?:         string;
  Email?:            string;
  Direccion?:        string;
  CiudadResidencia?: string;
  PaisResidencia?:   string;
  CodigoPostal?:     string;
  Ocupacion?:        string;
  EstadoCivil?:      string;
  FechaRegistro?:    string;
}

/** DDL: perfiles_viajero */
export interface BE_PerfilViajero {
  IdPerfil:            number;
  IdPasajero:          number;
  TipoPerfil?:         string;  // FRECUENTE | OCASIONAL | VIP | CORPORATIVO
  NumeroPrograma?:     string;
  PuntosAcumulados?:   number;
  Categoria?:          string;
  FechaIngreso?:       string;
  FechaUltimaActividad?: string;
}

// ── MÓDULO 8: RESERVAS Y BOLETERÍA ───────────────────────────────────────────

/** DDL: reservas */
export interface BE_Reserva {
  IdReserva:               number;
  IdVuelo:                 number;
  IdPasajero:              number;
  CodigoReserva:           string;
  FechaReserva?:           string;
  FechaModificacion?:      string;
  EstadoReserva:           string;  // CONFIRMADA|PENDIENTE|CANCELADA|CHECK_IN|ABORDADO|NO_SHOW
  TipoTarifa?:             string;
  PrecioPagado:            number;
  Moneda?:                 string;
  NumeroAsiento?:          string;
  ClaseServicio?:          string;
  EquipajeFacturadoKg?:    number;
  EquipajeManoKg?:         number;
  CheckinRealizado:        number;
  FechaCheckin?:           string;
  PuertaEmbarqueAsignada?: string;
  GrupoEmbarque?:          number;
  Observaciones?:          string;
}

/** DDL: metodos_pago */
export interface BE_MetodoPago {
  IdMetodoPago: number;
  Descripcion:  string;
  TipoPago?:    string;  // TARJETA_CREDITO | TARJETA_DEBITO | EFECTIVO | TRANSFERENCIA | PUNTOS
  Procesador?:  string;
  Activo:       number;
}

/** DDL: reservas_pagos */
export interface BE_ReservaPago {
  IdPago:              number;
  IdReserva:           number;
  IdMetodoPago?:       number;
  Monto:               number;
  Moneda?:             string;
  FechaPago?:          string;
  CodigoTransaccion?:  string;
  EstadoPago?:         string;
}

/** DDL: facturas */
export interface BE_Factura {
  IdFactura:    number;
  IdReserva:    number;
  NumeroFactura?: string;
  FechaEmision?: string;
  Subtotal:     number;
  Impuestos:    number;
  Total:        number;
  Moneda?:      string;
  DatosFiscales?: string;
}

/** DDL: promociones */
export interface BE_Promocion {
  IdPromocion:       number;
  CodigoPromocion?:  string;
  NombrePromocion?:  string;
  DescripcionPromocion?: string;
  TipoDescuento?:    string;  // PORCENTAJE | MONTO_FIJO | 2X1 | OTRO
  ValorDescuento?:   number;
  FechaInicio?:      string;
  FechaFin?:         string;
  UsoMaximo?:        number;
  UsosActuales?:     number;
  Activa?:           number;
}

/** DDL: solicitudes_especiales */
export interface BE_SolicitudEspecial {
  IdSolicitud:      number;
  IdReserva:        number;
  TipoSolicitud?:   string;  // COMIDA_ESPECIAL | ASISTENCIA | EQUIPAJE_ESPECIAL | MASCOTA | …
  Descripcion?:     string;
  FechaSolicitud?:  string;
  EstadoSolicitud?: string;
  Resolucion?:      string;
}

// ── MÓDULO 9: CHECK-IN Y ABORDAJE ────────────────────────────────────────────

/** DDL: checkin_digital */
export interface BE_CheckinDigital {
  IdCheckin:              number;
  IdReserva:              number;
  FechaCheckin?:          string;
  IpOrigen?:              string;
  Dispositivo?:           string;
  PaseAbordajeGenerado:   number;
  EnviadoEmail:           number;
  EnviadoSms:             number;
}

/** DDL: pases_abordaje */
export interface BE_PaseAbordaje {
  IdPaseAbordaje:  number;
  IdReserva:       number;
  CodigoBarras?:   string;
  FechaGeneracion?: string;
  PuertaEmbarque?: string;
  GrupoEmbarque?:  string;
  Asiento?:        string;
  Utilizado:       number;
  // Derived/denormalized fields some APIs may include:
  NumeroVuelo?:    string;
  NombrePasajero?: string;
  Terminal?:       string;
  HoraEmbarque?:   string;
}

/** DDL: control_abordaje */
export interface BE_ControlAbordaje {
  IdControlAbordaje: number;
  IdVuelo:           number;
  IdReserva:         number;
  HoraAbordaje?:     string;
  VerificadoPor?:    number;
  Estado?:           string;  // ABORDADO | NO_ABORDADO
  Observaciones?:    string;
}

// ── MÓDULO 10: SEGURIDAD ─────────────────────────────────────────────────────

/** DDL: incidentes (seguridad aeroportuaria) */
export interface BE_Incidente {
  IdIncidente:        number;
  IdPasajero?:        number;
  IdVuelo?:           number;
  CodigoAeropuerto?:  string;
  FechaIncidente?:    string;
  HoraIncidente?:     string;
  TipoIncidente?:     string;  // ARRESTO | INFRACCION | INCIDENTE | EMERGENCIA_MEDICA | …
  NivelGravedad?:     string;  // BAJO | MEDIO | ALTO | CRITICO
  Descripcion:        string;
  LugarIncidente?:    string;
  AutoridadInvolucrada?: string;
  OificialACargo?:    string;
  Resolucion?:        string;
  Estado?:            string;
  RequiereSeguimiento?: number;
}

/** DDL: alertas_seguridad */
export interface BE_AlertaSeguridad {
  IdAlerta:             number;
  CodigoAeropuerto?:    string;
  NivelAlerta?:         string;  // VERDE | AMARILLO | NARANJA | ROJO
  FechaInicio?:         string;
  FechaFin?:            string;
  Motivo?:              string;
  MedidasAdicionales?:  string;
  Activa:               number;
  EmitidaPor?:          string;
}

/** DDL: prohibiciones_vuelo */
export interface BE_ProhibicionVuelo {
  IdProhibicion:    number;
  IdPasajero:       number;
  FechaProhibicion?: string;
  FechaInicio?:     string;
  FechaFin?:        string;
  Motivo?:          string;
  IdIncidente?:     number;
  AutoridadEmite?:  string;
  Activa:           number;
}

// ── MÓDULO 12: OBJETOS PERDIDOS ───────────────────────────────────────────────

/** DDL: objetos_perdidos */
export interface BE_ObjetoPerdido {
  IdObjeto:           number;
  Descripcion:        string;
  CategoriaObjeto?:   string;
  FechaReporte?:      string;
  LugarEncontrado?:   string;  // AEROPUERTO | VUELO | SALA_ESPERA | …
  IdVuelo?:           number;
  CodigoAeropuerto?:  string;
  Color?:             string;
  Marca?:             string;
  ValorEstimado?:     number;
  UbicacionActual?:   string;
  Estado?:            string;  // ENCONTRADO | ENTREGADO | ELIMINADO | EN_PROCESO
  FechaEntrega?:      string;
}

// ── MÓDULO 13: ÁREA COMERCIAL ─────────────────────────────────────────────────

/** DDL: concesiones_comerciales */
export interface BE_Concesion {
  IdConcesion:       number;
  CodigoAeropuerto?: string;
  NombreComercial:   string;
  TipoNegocio?:      string;  // RESTAURANTE | TIENDA | ALQUILER | SERVICIO | DUTY_FREE
  Empresa?:          string;
  CanonMensual?:     number;
  LocalNumero?:       string;
  AreaM2?:           number;
  Activo:            number;
}

/** DDL: salones_vip */
export interface BE_SalonVip {
  IdSalon:           number;
  CodigoAeropuerto?: string;
  NombreSalon:       string;
  Ubicacion?:        string;
  Capacidad?:        number;
  HorarioApertura?:  string;
  HorarioCierre?:    string;
  RequisitosAcceso?: string;
  Activo:            number;
}

// ── MÓDULO 14: SERVICIOS AL PASAJERO ─────────────────────────────────────────

/** DDL: hoteles_cercanos */
export interface BE_HotelCercano {
  IdHotel:             number;
  CodigoAeropuerto?:   string;
  NombreHotel:         string;
  Categoria?:          string;   // 1* | 2* | 3* | 4* | 5*
  Direccion?:          string;
  DistanciaKm?:        number;
  Telefono?:           string;
  Email?:              string;
  Website?:            string;
  TarifaNocheDesde?:   number;
  TieneShuttle?:       number;   // NUMBER(1)
  Activo?:             number;
}

/** DDL: transporte_terrestre */
export interface BE_TransporteTerresre {
  IdTransporte:        number;
  CodigoAeropuerto?:   string;
  TipoTransporte?:     string;  // TAXI | BUS | SHUTTLE | RENTA_AUTO | METRO
  Empresa?:            string;
  TelefonoContacto?:   string;
  TarifaEstimada?:     string;
  HorarioOperacion?:   string;
  Activo:              number;
}

/** DDL: servicios_aeropuerto */
export interface BE_ServicioAeropuerto {
  IdServicio:          number;
  CodigoAeropuerto?:   string;
  NombreServicio:      string;
  TipoServicio?:       string;  // BANCO | CAJERO | FARMACIA | WIFI | ADUANA | …
  Ubicacion?:          string;
  HorarioApertura?:    string;
  HorarioCierre?:      string;
  Disponible24h?:      number;
  Activo:              number;
}

/** DDL: programa_lealtad */
export interface BE_ProgramaLealtad {
  IdLealtad:             number;
  IdPasajero?:           number;
  NivelMembresia:        string;  // BRONCE | PLATA | ORO | PLATINO
  PuntosAcumulados:      number;
  PuntosCanjeables:      number;
  MillasAcumuladas:      number;
  FechaIngreso?:         string;
  FechaUltimaActividad?: string;
  BeneficiosActivos?:    string;
  TarjetaNumero?:        string;
  Activo:                number;
}

/** DDL: quejas_sugerencias */
export interface BE_QuejaSugerencia {
  IdQueja:          number;
  IdPasajero?:      number;
  IdVuelo?:         number;
  TipoContacto?:    string;  // QUEJA | SUGERENCIA | FELICITACION | RECLAMO
  FechaContacto?:   string;
  MedioRecepcion?:  string;
  Descripcion?:     string;
  AreaRelacionada?: string;
  Estado?:          string;
  Respuesta?:       string;
}

/** DDL: encuestas_satisfaccion */
export interface BE_Encuesta {
  IdEncuesta:          number;
  IdPasajero:          number;
  IdVuelo:             number;
  FechaEncuesta?:      string;
  PuntuacionGeneral?:  number;
  PuntuacionCheckin?:  number;
  PuntuacionAbordaje?: number;
  PuntuacionAtencion?: number;
  Comentarios?:        string;
  Recomienda?:         number;
}

/** DDL: atencion_especial */
export interface BE_AtencionEspecial {
  IdAtencion:           number;
  IdPasajero:           number;
  IdReserva:            number;
  TipoAtencion?:        string;  // SILLA_RUEDAS | ASISTENCIA_VISUAL | ASISTENCIA_AUDITIVA
  FechaSolicitud?:      string;
  AsistenteAsignado?:   string;
  Observaciones?:       string;
}

// ── MÓDULO 15: RECURSOS HUMANOS ───────────────────────────────────────────────

/** DDL: empleados */
export interface BE_Empleado {
  IdEmpleado:         number;
  CodigoEmpleado:     string;
  Nombres:            string;
  Apellidos:          string;
  TipoDocumento?:     string;
  NumeroDocumento?:   string;
  FechaNacimiento?:   string;
  Nacionalidad?:      string;
  Genero?:            string;
  Direccion?:         string;
  Telefono?:          string;
  Email?:             string;
  FechaContratacion?: string;
  Departamento?:      string;
  Cargo?:             string;
  SalarioBase?:       number;
  TipoContrato?:      string;   // PERMANENTE | TEMPORAL | PRACTICAS | CONSULTOR
  Activo:             number;
}

/** DDL: departamentos */
export interface BE_Departamento {
  IdDepartamento:      number;
  NombreDepartamento:  string;
  Descripcion?:        string;
  Ubicacion?:          string;
  PresupuestoAnual?:   number;
  GerenteId?:          number;
  Activo?:             number;
}

/** DDL: evaluaciones_desempeno */
export interface BE_Evaluacion {
  IdEvaluacion:               number;
  IdEmpleado:                 number;
  FechaEvaluacion?:           string;
  EvaluadorId?:               number;
  PeriodoEvaluado?:           string;
  PuntuacionTotal?:           number;
  PuntuacionProductividad?:   number;
  PuntuacionAsistencia?:      number;
  Comentarios?:               string;
}

/** DDL: vacaciones_permisos */
export interface BE_VacacionPermiso {
  IdSolicitud:       number;
  IdEmpleado:        number;
  TipoSolicitud?:    string;  // VACACIONES | PERMISO | LICENCIA | INCAPACIDAD
  FechaInicio?:      string;
  FechaFin?:         string;
  DiasSolicitados?:  number;
  Motivo?:           string;
  Estado?:           string;
  AutorizadoPor?:    number;
}

// ── MÓDULO 16: FINANZAS Y CONTABILIDAD ───────────────────────────────────────

/** DDL: ingresos */
export interface BE_Ingreso {
  IdIngreso:       number;
  Fecha:           string;
  Concepto:        string;           // ← DDL: concepto (antes Descripcion)
  TipoIngreso?:    string;           // TASA_EMBARQUE | CONCESIONES | ESTACIONAMIENTO | …
  IdConcesion?:    number;
  IdVuelo?:        number;
  Monto:           number;
  Moneda?:         string;
  MetodoPago?:     string;
  Comprobante?:    string;
  RegistradoPor?:  number;
}

/** DDL: gastos */
export interface BE_Gasto {
  IdGasto:          number;
  Fecha:            string;
  Concepto:         string;          // ← DDL: concepto
  TipoGasto?:       string;          // SERVICIOS | MANTENIMIENTO | PERSONAL | …
  IdDepartamento?:  number;
  Proveedor?:       string;
  Monto:            number;
  Moneda?:          string;
  Factura?:         string;
  AutorizadoPor?:   number;
}

/** DDL: proveedores */
export interface BE_Proveedor {
  IdProveedor:       number;
  NombreProveedor:   string;
  TipoProveedor?:    string;  // COMBUSTIBLE | CATERING | MANTENIMIENTO | LIMPIEZA | …
  Nit?:              string;
  Direccion?:        string;
  Telefono?:         string;
  Email?:            string;
  ContactoNombre?:   string;
  CondicionesPago?:  string;
  Calificacion?:     number;
  Activo:            number;
}

/** DDL: tasas_aeroportuarias */
export interface BE_TasaAeroportuaria {
  IdTasa:              number;
  NombreTasa:          string;
  TipoTasa?:           string;  // INTERNACIONAL | NACIONAL | SEGURIDAD | …
  Monto:               number;
  Moneda?:             string;
  CalculoPorcentaje?:  number;
  AplicaA?:            string;  // PASAJERO | AEROLINEA | CARGA | AVION
  Activa:              number;
}

/** DDL: cuentas_bancarias */
export interface BE_CuentaBancaria {
  IdCuenta:      number;
  Banco?:        string;
  TipoCuenta?:   string;  // MONETARIA | AHORRO | INVERSION
  NumeroCuenta?: string;
  Moneda?:       string;
  SaldoActual?:  number;
  Estado?:       string;
}

/** DDL: movimientos_bancarios */
export interface BE_MovimientoBancario {
  IdMovimiento:      number;
  IdCuenta:          number;
  Fecha?:            string;
  TipoMovimiento?:   string;  // DEPOSITO | RETIRO | TRANSFERENCIA | PAGO | COBRO
  Concepto?:         string;
  Monto:             number;
  SaldoResultante?:  number;
  Referencia?:       string;
  Conciliado?:       number;
}

// ── MÓDULO 18: MENORES Y GRUPOS ESPECIALES ───────────────────────────────────

/** DDL: menores_no_acompanados */
export interface BE_MenorNoAcompanado {
  IdMenor:                number;
  IdReserva?:             number;
  Edad?:                  number;
  NombreEntregaOrigen?:   string;
  RelacionOrigen?:        string;
  TelefonoOrigen?:        string;
  NombreRecogeDestino?:   string;
  RelacionDestino?:       string;
  TelefonoDestino?:       string;
  Observaciones?:         string;
}

// ── MÓDULO 19: GESTIÓN DE CARGA ──────────────────────────────────────────────

/** DDL: envios_carga */
export interface BE_EnvioCarga {
  IdEnvio:                  number;
  CodigoEnvio:              string;
  IdVuelo:                  number;
  IdTipoCarga:              number;
  PesoKg:                   number;
  VolumenM3?:               number;
  CantidadBultos?:          number;
  Contenido:                string;
  ValorDeclarado?:          number;
  ConsignadorNombre?:       string;
  ConsignatarioNombre?:     string;
  InstruccionesEspeciales?: string;
  FechaRecepcion?:          string;
  Estado?:                  string;  // RECIBIDO | EN_BODEGA | CARGADO | EN_VUELO | ENTREGADO | …
  UbicacionActual?:         string;
}

/** DDL: manifiestos_carga */
export interface BE_ManifiestoCarga {
  IdManifiesto:      number;
  NumeroManifiesto:  string;
  IdVuelo:           number;
  FechaEmision?:     string;
  TotalBultos?:      number;
  PesoTotalKg?:      number;
  Estado?:           string;  // EMITIDO | VALIDADO | CERRADO
}

/** DDL: seguimiento_carga */
export interface BE_SeguimientoCarga {
  IdSeguimiento:         number;
  IdEnvio:               number;
  FechaHora?:            string;
  Ubicacion:             string;
  Estado:                string;
  Responsable?:          string;
  Observaciones?:        string;
  TemperaturaRegistrada?: number;
  Incidente?:            number;
}

// ── MÓDULO 20: MANTENIMIENTO PREDICTIVO ──────────────────────────────────────

/** DDL: ordenes_mantenimiento_predictivo */
export interface BE_OrdenMantenimiento {
  IdOrdenMp:            number;
  IdAlertaTecnica?:     number;
  IdPieza?:             number;
  IdAvionMatricula?:    string;
  FechaCreacion?:       string;
  Prioridad?:           string;  // BAJA | MEDIA | ALTA | URGENTE
  DescripcionTrabajo?:  string;
  TecnicoAsignado?:     number;
  Estado?:              string;  // PENDIENTE | ASIGNADO | EN_PROCESO | COMPLETADO | CANCELADO
  CostoEstimado?:       number;
  CostoReal?:           number;
}

/** DDL: alertas_tecnicas */
export interface BE_AlertaTecnica {
  IdAlertaTecnica:  number;
  IdLectura?:       number;
  NivelAlerta?:     string;   // INFORMATIVO | PREVENTIVO | CRITICO | EMERGENCIA
  TipoAlerta?:      string;
  Descripcion:      string;
  ValorUmbral?:     number;
  ValorActual?:     number;
  FechaAlerta?:     string;
  Atendida?:        number;
}

/** DDL: piezas_reemplazo */
export interface BE_PiezaReemplazo {
  IdPieza:           number;
  CodigoPieza:       string;
  NombrePieza:       string;
  Descripcion?:      string;
  IdModeloAvion?:    number;
  StockActual?:      number;
  StockMinimo?:      number;
  PrecioUnitario?:   number;
  TiempoReordenDias?: number;
}

// ── MÓDULO 27: TRANSPORTE TERRESTRE AMPLIADO ─────────────────────────────────

/** DDL: reservas_transporte_terrestre */
export interface BE_ReservaTransporte {
  IdReservaTransporte:   number;
  CodigoReservaTransporte: string;
  IdPasajero:            number;
  IdRutaTransporte:      number;
  TipoServicio?:         string;  // COMPARTIDO | PRIVADO | GRUPAL
  FechaServicio?:        string;
  HoraRecogida?:         string;
  LugarRecogida:         string;
  LugarDestino:          string;
  NumeroPasajeros?:      number;
  IdVueloAsociado?:      number;
  EstadoReserva?:        string;  // CONFIRMADA | ASIGNADA | COMPLETADA | CANCELADA | NO_SHOW
  PrecioTotal?:          number;
  Moneda?:               string;
  Pagado?:               number;
}

/** DDL: empresas_transporte */
export interface BE_EmpresaTransporte {
  IdEmpresaTransporte:     number;
  NombreEmpresa:           string;
  TipoEmpresa?:            string;  // TAXI | BUS | RENTA_CAR | SHUTTLE | TRANSFER
  TelefonoContacto?:       string;
  CalificacionPromedio?:   number;
  AutorizadaAeropuerto?:   number;
  Activa:                  number;
}

/** DDL: convenios_hoteles_transporte */
export interface BE_ConvenioHotelTransporte {
  IdConvenioHotel:     number;
  IdHotelCercano:      number;
  IdEmpresaTransporte: number;
  TipoConvenio?:       string;  // SHUTTLE_GRATUITO | TARIFA_PREFERENCIAL | EXCLUSIVO
  TarifaEspecial?:     number;
  Condiciones?:        string;
  FechaInicio:         string;
  FechaFin?:           string;
  Activo:              number;
}

// ── MÓDULO 22: GESTIÓN DE COMBUSTIBLE ────────────────────────────────────────

/** DDL: tanques_combustible */
export interface BE_TanqueCombustible {
  IdTanque:                 number;
  CodigoTanque:             string;
  NombreTanque?:            string;
  TipoCombustible?:         string;  // JET_A | JET_A1 | JET_B | AVGAS
  CapacidadLitros:          number;
  NivelActualLitros?:       number;
  PorcentajeLlenado?:       number;
  FechaUltimaInspeccion?:   string;
  Activo:                   number;
}

/** DDL: cargas_combustible */
export interface BE_CargaCombustible {
  IdCargaCombustible:   number;
  IdPedidoCombustible:  number;
  IdSurtidor?:          number;
  CantidadRealLitros:   number;
  FechaInicioCarga?:    string;
  FechaFinCarga?:       string;
  DuracionMinutos?:     number;
  OperadorCarga?:       number;
  IncidenciaTecnica?:   number;
  Observaciones?:       string;
}

// ── MÓDULO 24: SEGURIDAD INFORMÁTICA ─────────────────────────────────────────

/** DDL: usuarios_sistema */
export interface BE_UsuarioSistema {
  IdUsuarioSistema:     number;
  IdEmpleado?:          number;
  NombreUsuario:        string;
  EmailInstitucional?:  string;
  FechaCreacion?:       string;
  FechaUltimoAcceso?:   string;
  Bloqueado?:           number;
  RequiereCambioPassword?: number;
  Activo:               number;
}

/** DDL: logs_acceso_sistema */
export interface BE_LogAcceso {
  IdLogAcceso:      number;
  IdUsuarioSistema: number;
  TimestampAcceso?: string;
  IpOrigen?:        string;
  Dispositivo?:     string;
  TipoAcceso?:      string;  // LOGIN | LOGOUT | LOGIN_FALLIDO
  Resultado?:       string;  // EXITOSO | FALLIDO | BLOQUEADO
}

// ── MÓDULO 25: MARKETING Y FIDELIZACIÓN ──────────────────────────────────────

/** DDL: campanas_marketing */
export interface BE_CampanaMarketing {
  IdCampanaMarketing: number;
  NombreCampana:      string;
  TipoCampana?:       string;  // EMAIL | SMS | REDES_SOCIALES | WEB | APP | …
  Objetivo?:          string;  // VENTAS | FIDELIZACION | NOTORIEDAD | LANZAMIENTO
  FechaInicio:        string;
  FechaFin:           string;
  Presupuesto?:       number;
  Activa:             number;
}

/** DDL: canjes_puntos */
export interface BE_CanjePuntos {
  IdCanjePuntos:     number;
  IdPasajero:        number;
  IdLealtad:         number;
  FechaCanje?:       string;
  PuntosUtilizados:  number;
  TipoCanje?:        string;  // VUELO | UPGRADE | PRODUCTO | SERVICIO | EQUIPAJE_EXTRA
  IdVuelo?:          number;
  ValorMonetario?:   number;
  EstadoCanje?:      string;  // PROCESADO | ENTREGADO | CANCELADO
}

// ── TIPOS REQUEST — Stored Procedures (lógica de negocio) ────────────────────

export interface BE_CrearReservaRequest {
  IdVuelo: number; IdPasajero: number; ClaseServicio: string;
  NumeroAsiento: string; TipoTarifa: string; Precio: number; Moneda: string;
}

export interface BE_CheckInRequest {
  CodigoReserva: string; NumeroDocumento: string; NumeroAsiento: string;
}

export interface BE_CheckInMostradorRequest {
  CodigoReserva: string; NumeroDocumento: string; NumeroAsiento: string;
  EquipajeFacturado: number; EquipajeMano: number; TipoVuelo: string; VisaValida: number;
}

export interface BE_EmbarqueRequest {
  CodigoReserva: string; NumeroDocumento: string; PuertaEmbarque: string;
}

export interface BE_PagoBoletoRequest {
  IdReserva: number; IdMetodoPago: number; Monto: number;
  Moneda: string; CodigoTransaccion: string; Comprobante?: string;
}

export interface BE_AsignarPuertaRequest {
  IdVuelo: number; IdPuerta: number; TipoVuelo: string;
}

export interface BE_CancelarVueloRequest {
  IdVuelo: number; MotivoCancelacion: string;
}

export interface BE_CrearVueloRequest {
  IdPrograma: number; FechaVuelo: string; HoraSalida: string;
  HoraLlegada: string; IdModeloAvion: number; MatriculaAvion: string;
}

export interface BE_ReprogramarVueloRequest {
  IdVuelo: number; NuevaFecha: string; NuevaHoraSalida: string; NuevaHoraLlegada: string;
}

export interface BE_RegistrarAerolineaRequest {
  Nombre: string; CodigoIata: string; CodigoOaci: string; PaisOrigen: string; Contacto: string;
}

export interface BE_RegistrarAeronaveRequest {
  Matricula: string; CodigoIcaoTipo: string; IdAerolinea: number;
  NombreAeronave?: string; Configuracion: string; NumeroMotores: number; AnioFabricacion: number;
}

export interface BE_RegistrarPasajeroRequest {
  Nombre: string; Apellidos: string; NumeroDocumento: string;
  Nacionalidad: string; FechaNacimiento: string; Email?: string;
}

// ── HEALTH CHECK ──────────────────────────────────────────────────────────────
export interface BE_HealthCheck { status: string; database: string; }

// ═══════════════════════════════════════════════════════════════════════════════
// NORMALIZERS — PascalCase → snake_case para consistencia interna del frontend
// ═══════════════════════════════════════════════════════════════════════════════
export const norm = {
  aeropuerto: (a: BE_Aeropuerto) => ({
    codigo_aeropuerto: a.CodigoAeropuerto, nombre: a.Nombre,
    ciudad: a.Ciudad, pais: a.Pais, region: a.Region,
    latitud: a.Latitud, longitud: a.Longitud,
    terminales: a.Terminales, puertas_abordaje: a.PuertasAbordaje,
    activo: a.Activo,
  }),
  aerolinea: (a: BE_Aerolinea) => ({
    id_aerolinea: a.IdAerolinea, nombre_aerolinea: a.NombreAerolinea,
    codigo_iata: a.CodigoIata, codigo_oaci: a.CodigoOaci,
    pais_origen: a.PaisOrigen, flota_total: a.FlotaTotal,
    alianza: a.Alianza, activo: a.Activo,
  }),
  vuelo: (v: BE_Vuelo) => ({
    id_vuelo: v.IdVuelo, id_programa: v.IdPrograma,
    numero_vuelo: v.NumeroVuelo,
    aeropuerto_origen: v.AeropuertoOrigen,
    aeropuerto_destino: v.AeropuertoDestino,
    hora_salida_programada: v.HoraSalidaProgramada,
    hora_llegada_programada: v.HoraLlegadaProgramada,
    hora_salida_real: v.HoraSalidaReal,
    hora_llegada_real: v.HoraLlegadaReal,
    plazas_vacias: v.PlazasVacias, plazas_ocupadas: v.PlazasOcupadas,
    estado_vuelo: v.EstadoVuelo, matricula_avion: v.MatriculaAvion,
    nombre_aerolinea: v.NombreAerolinea, codigo_iata: v.CodigoIata,
    duracion_minutos: v.DuracionMinutos,
  }),
  pasajero: (p: BE_Pasajero) => ({
    id_pasajero: p.IdPasajero, nombres: p.Nombres, apellidos: p.Apellidos,
    tipo_documento: p.TipoDocumento, numero_documento: p.NumeroDocumento,
    email: p.Email, telefono: p.Telefono, nacionalidad: p.Nacionalidad,
    fecha_nacimiento: p.FechaNacimiento, genero: p.Genero,
  }),
  reserva: (r: BE_Reserva) => ({
    id_reserva: r.IdReserva, id_vuelo: r.IdVuelo, id_pasajero: r.IdPasajero,
    codigo_reserva: r.CodigoReserva, estado_reserva: r.EstadoReserva,
    precio_pagado: r.PrecioPagado, moneda: r.Moneda,
    numero_asiento: r.NumeroAsiento, clase_servicio: r.ClaseServicio,
    equipaje_facturado_kg: r.EquipajeFacturadoKg,
    equipaje_mano_kg: r.EquipajeManoKg,
    checkin_realizado: r.CheckinRealizado, fecha_checkin: r.FechaCheckin,
    puerta_embarque_asignada: r.PuertaEmbarqueAsignada,
    grupo_embarque: r.GrupoEmbarque,
  }),
  lealtad: (l: BE_ProgramaLealtad) => ({
    id_lealtad: l.IdLealtad, id_pasajero: l.IdPasajero,
    nivel_membresia: l.NivelMembresia, puntos_acumulados: l.PuntosAcumulados,
    puntos_canjeables: l.PuntosCanjeables, millas_acumuladas: l.MillasAcumuladas,
    tarjeta_numero: l.TarjetaNumero, activo: l.Activo,
  }),
  hotel: (h: BE_HotelCercano) => ({
    id_hotel: h.IdHotel, codigo_aeropuerto: h.CodigoAeropuerto,
    nombre_hotel: h.NombreHotel, categoria: h.Categoria,
    direccion: h.Direccion, distancia_km: h.DistanciaKm,
    tarifa_noche_desde: h.TarifaNocheDesde,
    tiene_shuttle: h.TieneShuttle, activo: h.Activo,
  }),
  empleado: (e: BE_Empleado) => ({
    id_empleado: e.IdEmpleado, codigo: e.CodigoEmpleado,
    nombres: e.Nombres, apellidos: e.Apellidos,
    email: e.Email, telefono: e.Telefono,
    departamento: e.Departamento, cargo: e.Cargo,
    salario_base: e.SalarioBase, activo: e.Activo,
  }),
  ingreso: (i: BE_Ingreso) => ({
    id_ingreso: i.IdIngreso, fecha: i.Fecha,
    concepto: i.Concepto, tipo_ingreso: i.TipoIngreso,
    monto: i.Monto, moneda: i.Moneda, metodo_pago: i.MetodoPago,
  }),
  gasto: (g: BE_Gasto) => ({
    id_gasto: g.IdGasto, fecha: g.Fecha,
    concepto: g.Concepto, tipo_gasto: g.TipoGasto,
    monto: g.Monto, proveedor: g.Proveedor,
  }),
  promocion: (p: BE_Promocion) => ({
    id_promocion: p.IdPromocion, codigo: p.CodigoPromocion,
    nombre: p.NombrePromocion, descripcion: p.DescripcionPromocion,
    tipo_descuento: p.TipoDescuento, valor_descuento: p.ValorDescuento,
    fecha_inicio: p.FechaInicio, fecha_fin: p.FechaFin,
    usos_actuales: p.UsosActuales, uso_maximo: p.UsoMaximo, activa: p.Activa,
  }),
};

// ═══════════════════════════════════════════════════════════════════════════════
// API SURFACE — Organizado por backend + módulo DDL
// ═══════════════════════════════════════════════════════════════════════════════
export const backendApi = {

  // ── DEVELOP BACKEND (:5087) — Módulos 1-6, 21-29 ─────────────────────────

  // Módulo 1
  health:       () => get<BE_HealthCheck>(BE_DEVELOP, '/api/test'),
  aeropuertos: {
    listar:     () => get<BE_Aeropuerto[]>(BE_DEVELOP, '/api/aeropuertos'),
    obtener:    (cod: string) => get<BE_Aeropuerto>(BE_DEVELOP, `/api/aeropuertos/${cod}`),
    crear:      (m: Omit<BE_Aeropuerto, 'FechaRegistro'>) => post(BE_DEVELOP, '/api/aeropuertos', m),
    actualizar: (cod: string, m: Partial<BE_Aeropuerto>) => put(BE_DEVELOP, `/api/aeropuertos/${cod}`, m),
    eliminar:   (cod: string) => del(BE_DEVELOP, `/api/aeropuertos/${cod}`),
  },
  puertas: {
    listar:       () => get<BE_PuertaEmbarque[]>(BE_DEVELOP, '/api/puertasembarque'),
    porAeropuerto:(cod: string) => get<BE_PuertaEmbarque[]>(BE_DEVELOP, `/api/puertasembarque/aeropuerto/${cod}`),
  },

  // Módulo 2
  aviones: {
    listar:     () => get<any[]>(BE_DEVELOP, '/api/aviones'),
    obtener:    (matricula: string) => get<any>(BE_DEVELOP, `/api/aviones/${matricula}`),
    crear:      (m: any) => post(BE_DEVELOP, '/api/aviones', m),
    actualizar: (matricula: string, m: any) => put(BE_DEVELOP, `/api/aviones/${matricula}`, m),
  },
  modelosAvion: {
    listar:     () => get<BE_ModeloAvion[]>(BE_DEVELOP, '/api/modelosaviones'),
    obtener:    (id: number) => get<BE_ModeloAvion>(BE_DEVELOP, `/api/modelosaviones/${id}`),
  },
  mantenimientoAviones: {
    listar:     () => get<BE_MantenimientoAvion[]>(BE_DEVELOP, '/api/mantenimientoaviones'),
    crear:      (m: Omit<BE_MantenimientoAvion, 'IdMantenimiento'>) =>
      post(BE_DEVELOP, '/api/mantenimientoaviones', m),
  },

  // Módulo 1 extra (pistas, terminales, hangares)
  pistas: {
    listar:       () => get<BE_Pista[]>(BE_DEVELOP, '/api/pistasaterrizaje'),
    porAeropuerto:(cod: string) => get<BE_Pista[]>(BE_DEVELOP, `/api/pistasaterrizaje/aeropuerto/${cod}`),
    crear:        (m: any) => post(BE_DEVELOP, '/api/pistasaterrizaje', m),
  },
  terminales: {
    listar:       () => get<any[]>(BE_DEVELOP, '/api/terminalesaeropuerto'),
    porAeropuerto:(cod: string) => get<any[]>(BE_DEVELOP, `/api/terminalesaeropuerto/aeropuerto/${cod}`),
    crear:        (m: any) => post(BE_DEVELOP, '/api/terminalesaeropuerto', m),
  },
  hangares: {
    listar:       () => get<any[]>(BE_DEVELOP, '/api/hangares'),
    crear:        (m: any) => post(BE_DEVELOP, '/api/hangares', m),
  },

  // Módulo 3
  aerolineas: {
    listar:           () => get<BE_Aerolinea[]>(BE_DEVELOP, '/api/aerolineas'),
    obtener:          (id: number) => get<BE_Aerolinea>(BE_DEVELOP, `/api/aerolineas/${id}`),
    crear:            (m: Omit<BE_Aerolinea, 'IdAerolinea'>) => post(BE_DEVELOP, '/api/aerolineas', m),
    actualizar:       (id: number, m: Partial<BE_Aerolinea>) => put(BE_DEVELOP, `/api/aerolineas/${id}`, m),
    eliminar:         (id: number) => del(BE_DEVELOP, `/api/aerolineas/${id}`),
    registrar:        (m: BE_RegistrarAerolineaRequest) =>
      post<{ mensaje: string }>(BE_DEVELOP, '/api/aerolineas/registrar', m),
    registrarAeronave:(m: BE_RegistrarAeronaveRequest) =>
      post<{ mensaje: string }>(BE_DEVELOP, '/api/aerolineas/registrar_aeronave', m),
  },
  tiposAerolinea: {
    listar:     () => get<BE_TipoAerolinea[]>(BE_DEVELOP, '/api/tiposaerolinea'),
    crear:      (m: Omit<BE_TipoAerolinea, 'IdTipoAerolinea'>) => post(BE_DEVELOP, '/api/tiposaerolinea', m),
  },
  franquiciasEquipaje: {
    listar:         () => get<BE_FranquiciaEquipaje[]>(BE_DEVELOP, '/api/franquiciasequipaje'),
    porAerolinea:   (id: number) => get<BE_FranquiciaEquipaje[]>(BE_DEVELOP, `/api/franquiciasequipaje/aerolinea/${id}`),
  },

  // Módulo 4
  programasVuelo: {
    listar:     () => get<BE_ProgramaVuelo[]>(BE_DEVELOP, '/api/programasvuelo'),
    obtener:    (id: number) => get<BE_ProgramaVuelo>(BE_DEVELOP, `/api/programasvuelo/${id}`),
    buscar:     (origen: string, destino: string) =>
      get<BE_ProgramaVuelo[]>(BE_DEVELOP, `/api/programasvuelo?origen=${origen}&destino=${destino}`),
    crear:      (m: Omit<BE_ProgramaVuelo, 'IdPrograma'>) => post(BE_DEVELOP, '/api/programasvuelo', m),
    actualizar: (id: number, m: Partial<BE_ProgramaVuelo>) => put(BE_DEVELOP, `/api/programasvuelo/${id}`, m),
  },
  temporadas: {
    listar:     () => get<BE_TemporadaVuelo[]>(BE_DEVELOP, '/api/temporadavuelo'),
    obtener:    (id: number) => get<BE_TemporadaVuelo>(BE_DEVELOP, `/api/temporadavuelo/${id}`),
    crear:      (m: Omit<BE_TemporadaVuelo, 'IdTemporada'>) => post(BE_DEVELOP, '/api/temporadavuelo', m),
    actualizar: (id: number, m: Partial<BE_TemporadaVuelo>) => put(BE_DEVELOP, `/api/temporadavuelo/${id}`, m),
  },
  tarifasVuelo: {
    listar:     () => get<any[]>(BE_DEVELOP, '/api/tarifasvuelo'),
    porPrograma:(id: number) => get<any[]>(BE_DEVELOP, `/api/tarifasvuelo/programa/${id}`),
    crear:      (m: any) => post(BE_DEVELOP, '/api/tarifasvuelo', m),
    actualizar: (id: number, m: any) => put(BE_DEVELOP, `/api/tarifasvuelo/${id}`, m),
  },
  frecuenciasVuelo: {
    listar:     () => get<any[]>(BE_DEVELOP, '/api/frecuenciasvuelo'),
    porPrograma:(id: number) => get<any[]>(BE_DEVELOP, `/api/frecuenciasvuelo/programa/${id}`),
    crear:      (m: any) => post(BE_DEVELOP, '/api/frecuenciasvuelo', m),
  },

  // Módulo 5
  vuelos: {
    listar:          () => get<BE_Vuelo[]>(BE_DEVELOP, '/api/vuelos'),
    obtener:         (id: number) => get<BE_Vuelo>(BE_DEVELOP, `/api/vuelos/${id}`),
    buscar:          (origen: string, destino: string, fecha: string) =>
      get<BE_Vuelo[]>(BE_DEVELOP, `/api/vuelos?origen=${origen}&destino=${destino}&fecha=${fecha}`),
    crear:           (m: Omit<BE_Vuelo, 'IdVuelo'>) => post<{ IdGenerado: number }>(BE_DEVELOP, '/api/vuelos', m),
    actualizar:      (id: number, m: Partial<BE_Vuelo>) => put(BE_DEVELOP, `/api/vuelos/${id}`, m),
    actualizarEstado:(id: number, estado: string) =>
      put(BE_DEVELOP, `/api/vuelos/${id}/estado`, { EstadoVuelo: estado }),
    crearVuelo:      (m: BE_CrearVueloRequest) =>
      post<{ mensaje: string }>(BE_DEVELOP, '/api/vuelos/crear-vuelo', m),
    reprogramar:     (m: BE_ReprogramarVueloRequest) =>
      put<{ mensaje: string }>(BE_DEVELOP, '/api/vuelos/reprogramar', m),
    asignarPuerta:   (m: BE_AsignarPuertaRequest) =>
      post<{ mensaje: string }>(BE_DEVELOP, '/api/vuelos/asignar-puerta', m),
    cancelar:        (m: BE_CancelarVueloRequest) =>
      post<{ mensaje: string }>(BE_DEVELOP, '/api/vuelos/cancelar', m),
    cerrarEmbarque:  (idVuelo: number) =>
      post<{ mensaje: string }>(BE_DEVELOP, `/api/vuelos/${idVuelo}/cerrar-embarque`, {}),
  },
  incidentesVuelo: {
    listar:     () => get<BE_IncidenteVuelo[]>(BE_DEVELOP, '/api/incidentesvuelo'),
    porVuelo:   (id: number) => get<BE_IncidenteVuelo[]>(BE_DEVELOP, `/api/incidentesvuelo/vuelo/${id}`),
    crear:      (m: Omit<BE_IncidenteVuelo, 'IdIncidenteVuelo'>) => post(BE_DEVELOP, '/api/incidentesvuelo', m),
  },
  retrasos: {
    listar:     () => get<BE_RetrasoVuelo[]>(BE_DEVELOP, '/api/retrasosvuelo'),
    porVuelo:   (id: number) => get<BE_RetrasoVuelo[]>(BE_DEVELOP, `/api/retrasosvuelo/vuelo/${id}`),
    crear:      (m: Omit<BE_RetrasoVuelo, 'IdRetraso'>) => post(BE_DEVELOP, '/api/retrasosvuelo', m),
  },
  meteorologia: {
    listar:        () => get<BE_Meteorologia[]>(BE_DEVELOP, '/api/condicionesmeteorologicas'),
    porAeropuerto: (cod: string) =>
      get<BE_Meteorologia[]>(BE_DEVELOP, `/api/condicionesmeteorologicas/aeropuerto/${cod}`),
    crear:         (m: Omit<BE_Meteorologia, 'IdCondicion'>) => post(BE_DEVELOP, '/api/condicionesmeteorologicas', m),
  },

  // Módulo 6
  tripulacion: {
    listar:     () => get<BE_Tripulante[]>(BE_DEVELOP, '/api/tripulacion'),
    obtener:    (id: number) => get<BE_Tripulante>(BE_DEVELOP, `/api/tripulacion/${id}`),
    crear:      (m: Omit<BE_Tripulante, 'IdTripulante'>) => post(BE_DEVELOP, '/api/tripulacion', m),
    actualizar: (id: number, m: Partial<BE_Tripulante>) => put(BE_DEVELOP, `/api/tripulacion/${id}`, m),
    eliminar:   (id: number) => del(BE_DEVELOP, `/api/tripulacion/${id}`),
  },

  tripulacionVuelo: {
    porVuelo:   (id: number) => get<any[]>(BE_DEVELOP, `/api/tripulacionvuelo/vuelo/${id}`),
    listar:     () => get<any[]>(BE_DEVELOP, '/api/tripulacionvuelo'),
    asignar:    (m: any) => post(BE_DEVELOP, '/api/tripulacionvuelo', m),
    eliminar:   (id: number) => del(BE_DEVELOP, `/api/tripulacionvuelo/${id}`),
  },

  // Módulo 21 — Tiempo Real
  tiempoReal: {
    slots: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/slotaeropuerto'),
      porFecha:   (fecha: string) => get<any[]>(BE_DEVELOP, `/api/slotaeropuerto/fecha/${fecha}`),
      crear:      (m: any) => post(BE_DEVELOP, '/api/slotaeropuerto', m),
      actualizar: (id: number, m: any) => put(BE_DEVELOP, `/api/slotaeropuerto/${id}`, m),
    },
    retrasos: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/retrasostiemporeal'),
      activos:    () => get<any[]>(BE_DEVELOP, '/api/retrasostiemporeal/activos'),
      crear:      (m: any) => post(BE_DEVELOP, '/api/retrasostiemporeal', m),
    },
    asignacionPistas: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/asignacionpistastiemporeal'),
      activas:    () => get<any[]>(BE_DEVELOP, '/api/asignacionpistastiemporeal/activas'),
      crear:      (m: any) => post(BE_DEVELOP, '/api/asignacionpistastiemporeal', m),
    },
    capacidadTerminal: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/capacidadterminal'),
      actual:     (terminal: string) => get<any>(BE_DEVELOP, `/api/capacidadterminal/${terminal}`),
    },
    condicionesPista: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/condicionespista'),
      porPista:   (id: number) => get<any>(BE_DEVELOP, `/api/condicionespista/${id}`),
    },
    posicionesRadar: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/posicionesradar'),
      activas:    () => get<any[]>(BE_DEVELOP, '/api/posicionesradar/activas'),
    },
    torreControl: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/torrecontrol'),
      crear:      (m: any) => post(BE_DEVELOP, '/api/torrecontrol', m),
    },
    historialFlujo: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/historialflujotrafico'),
      porFecha:   (fecha: string) => get<any[]>(BE_DEVELOP, `/api/historialflujotrafico/fecha/${fecha}`),
    },
    prediccionDemanda: {
      listar:     () => get<any[]>(BE_DEVELOP, '/api/predicciondemanda'),
      porFecha:   (fecha: string) => get<any[]>(BE_DEVELOP, `/api/predicciondemanda/fecha/${fecha}`),
    },
    meteorologia: {
      listar:        () => get<BE_Meteorologia[]>(BE_DEVELOP, '/api/condicionesmeteorologicas'),
      porAeropuerto: (cod: string) =>
        get<BE_Meteorologia[]>(BE_DEVELOP, `/api/condicionesmeteorologicas/aeropuerto/${cod}`),
      crear:         (m: any) => post(BE_DEVELOP, '/api/condicionesmeteorologicas', m),
    },
  },

  // ── GERSON BACKEND (:5088) — Módulos 7-14 ────────────────────────────────

  // Módulo 7
  pasajeros: {
    listar:     () => get<BE_Pasajero[]>(BE_GERSON, '/api/pasajeros'),
    obtener:    (id: number) => get<BE_Pasajero>(BE_GERSON, `/api/pasajeros/${id}`),
    buscar:     (q: string) => get<BE_Pasajero[]>(BE_GERSON, `/api/pasajeros/buscar?q=${encodeURIComponent(q)}`),
    crear:      (m: Omit<BE_Pasajero, 'IdPasajero'>) => post<{ IdGenerado: number }>(BE_GERSON, '/api/pasajeros', m),
    actualizar: (id: number, m: Partial<BE_Pasajero>) => put(BE_GERSON, `/api/pasajeros/${id}`, m),
    registrar:  (m: BE_RegistrarPasajeroRequest) =>
      post<{ mensaje: string }>(BE_GERSON, '/api/pasajeros/registrar', m),
  },
  perfilesViajero: {
    porPasajero:(id: number) => get<BE_PerfilViajero>(BE_GERSON, `/api/perfilesviajero/pasajero/${id}`),
    actualizar: (id: number, m: Partial<BE_PerfilViajero>) => put(BE_GERSON, `/api/perfilesviajero/${id}`, m),
  },

  // Módulo 8
  reservas: {
    crear:                (m: Omit<BE_Reserva, 'IdReserva'>) =>
      post<{ IdGenerado: number; CodigoReserva: string }>(BE_GERSON, '/api/reservas', m),
    porPasajero:          (id: number) => get<BE_Reserva[]>(BE_GERSON, `/api/reservas/pasajero/${id}`),
    porCodigo:            (cod: string) => get<BE_Reserva>(BE_GERSON, `/api/reservas/${cod}`),
    cancelar:             (id: number) => put(BE_GERSON, `/api/reservas/${id}/cancelar`, {}),
    actualizar:           (id: number, m: Partial<BE_Reserva>) => put(BE_GERSON, `/api/reservas/${id}`, m),
    crearReserva:         (m: BE_CrearReservaRequest) =>
      post<{ mensaje: string }>(BE_GERSON, '/api/reservas/crear-reserva', m),
    checkIn:              (m: BE_CheckInRequest) =>
      post<{ mensaje: string; qr_provisional: string }>(BE_GERSON, '/api/reservas/check-in', m),
    checkInMostrador:     (m: BE_CheckInMostradorRequest) =>
      post<{ mensaje: string; detalle: string }>(BE_GERSON, '/api/reservas/check-in-mostrador', m),
    registrarAbordaje:    (m: BE_EmbarqueRequest) =>
      post<{ mensaje: string }>(BE_GERSON, '/api/reservas/registrar-abordaje', m),
    pagar:                (m: BE_PagoBoletoRequest) =>
      post<{ mensaje: string }>(BE_GERSON, '/api/reservas/pagar', m),
  },
  pagosReserva: {
    registrar:  (m: Omit<BE_ReservaPago, 'IdPago'>) =>
      post<{ IdGenerado: number }>(BE_GERSON, '/api/reservaspagos', m),
    porReserva: (id: number) => get<BE_ReservaPago[]>(BE_GERSON, `/api/reservaspagos/reserva/${id}`),
  },
  facturas: {
    porReserva: (idReserva: number) =>
      get<BE_Factura>(BE_GERSON, `/api/facturas/reserva/${idReserva}`),
  },
  metodosPago: {
    listar:     () => get<BE_MetodoPago[]>(BE_GERSON, '/api/metodospago'),
  },
  promociones: {
    listar:     () => get<BE_Promocion[]>(BE_GERSON, '/api/promociones'),
    obtener:    (id: number) => get<BE_Promocion>(BE_GERSON, `/api/promociones/${id}`),
    crear:      (m: Omit<BE_Promocion, 'IdPromocion'>) => post(BE_GERSON, '/api/promociones', m),
    aplicar:    (idReserva: number, codigo: string) =>
      post(BE_GERSON, '/api/promociones/aplicar', { IdReserva: idReserva, CodigoPromocion: codigo }),
  },
  solicitudesEspeciales: {
    crear:       (m: Omit<BE_SolicitudEspecial, 'IdSolicitud'>) => post(BE_GERSON, '/api/solicitudesespeciales', m),
    porReserva:  (id: number) => get<BE_SolicitudEspecial[]>(BE_GERSON, `/api/solicitudesespeciales/reserva/${id}`),
  },

  // Módulo 9
  checkin: {
    registrar:  (m: Omit<BE_CheckinDigital, 'IdCheckin'>) => post(BE_GERSON, '/api/checkindigital', m),
    obtener:    (idReserva: number) => get<BE_CheckinDigital>(BE_GERSON, `/api/checkindigital/${idReserva}`),
  },
  pasesAbordaje: {
    generar:    (m: Omit<BE_PaseAbordaje, 'IdPaseAbordaje'>) =>
      post<{ IdPase: number; CodigoBarras: string }>(BE_GERSON, '/api/pasesabordaje', m),
    obtener:    (idReserva: number) => get<BE_PaseAbordaje>(BE_GERSON, `/api/pasesabordaje/${idReserva}`),
  },
  controlAbordaje: {
    registrar:  (m: Omit<BE_ControlAbordaje, 'IdControlAbordaje'>) => post(BE_GERSON, '/api/controlabordaje', m),
    porVuelo:   (id: number) => get<BE_ControlAbordaje[]>(BE_GERSON, `/api/controlabordaje/vuelo/${id}`),
  },

  // Módulo 10
  incidentes: {
    listar:     () => get<BE_Incidente[]>(BE_GERSON, '/api/incidentes'),
    obtener:    (id: number) => get<BE_Incidente>(BE_GERSON, `/api/incidentes/${id}`),
    crear:      (m: Omit<BE_Incidente, 'IdIncidente'>) => post(BE_GERSON, '/api/incidentes', m),
    porPasajero:(id: number) => get<BE_Incidente[]>(BE_GERSON, `/api/incidentes/pasajero/${id}`),
  },
  alertasSeguridad: {
    listar:     () => get<BE_AlertaSeguridad[]>(BE_GERSON, '/api/alertasseguridad'),
    activas:    () => get<BE_AlertaSeguridad[]>(BE_GERSON, '/api/alertasseguridad/activas'),
    crear:      (m: Omit<BE_AlertaSeguridad, 'IdAlerta'>) => post(BE_GERSON, '/api/alertasseguridad', m),
  },
  prohibicionesVuelo: {
    porPasajero:(id: number) => get<BE_ProhibicionVuelo[]>(BE_GERSON, `/api/prohibicionesvuelo/pasajero/${id}`),
    crear:      (m: Omit<BE_ProhibicionVuelo, 'IdProhibicion'>) => post(BE_GERSON, '/api/prohibicionesvuelo', m),
  },

  // Módulo 12
  objetosPerdidos: {
    listar:     () => get<BE_ObjetoPerdido[]>(BE_GERSON, '/api/objetosperdidos'),
    crear:      (m: Omit<BE_ObjetoPerdido, 'IdObjeto'>) => post(BE_GERSON, '/api/objetosperdidos', m),
    entregar:   (id: number, idPasajero: number) =>
      put(BE_GERSON, `/api/objetosperdidos/${id}/entregar`, { IdPasajero: idPasajero }),
  },

  // Módulo 13
  concesiones: {
    listar:     () => get<BE_Concesion[]>(BE_GERSON, '/api/concesionescomerciales'),
  },
  salonesVip: {
    listar:     () => get<BE_SalonVip[]>(BE_GERSON, '/api/salonesvip'),
    acceder:    (idSalon: number, idPasajero: number, idVuelo: number) =>
      post(BE_GERSON, '/api/salonesvip/acceso', { IdSalon: idSalon, IdPasajero: idPasajero, IdVuelo: idVuelo }),
  },

  // Módulo 14
  hoteles: {
    listar:       () => get<BE_HotelCercano[]>(BE_GERSON, '/api/hotelescercanos'),
    porAeropuerto:(cod: string) =>
      get<BE_HotelCercano[]>(BE_GERSON, `/api/hotelescercanos/aeropuerto/${cod}`),
    registrar:    (m: Omit<BE_HotelCercano, 'IdHotel'>) => post(BE_GERSON, '/api/hotelescercanos', m),
  },
  transporte: {
    listar:       () => get<BE_TransporteTerresre[]>(BE_GERSON, '/api/transporteterrestre'),
    reservar:     (m: Omit<BE_ReservaTransporte, 'IdReservaTransporte'>) =>
      post<{ IdGenerado: number }>(BE_GERSON, '/api/reservastransporte', m),
    misReservas:  (idPasajero: number) =>
      get<BE_ReservaTransporte[]>(BE_GERSON, `/api/reservastransporte/pasajero/${idPasajero}`),
    empresas:     () => get<BE_EmpresaTransporte[]>(BE_GERSON, '/api/empresastransporte'),
    conveniosHotel:(idHotel: number) =>
      get<BE_ConvenioHotelTransporte[]>(BE_GERSON, `/api/conveniostransporte/hotel/${idHotel}`),
  },
  serviciosAeropuerto: {
    listar:       () => get<BE_ServicioAeropuerto[]>(BE_GERSON, '/api/serviciosaeropuerto'),
    porAeropuerto:(cod: string) =>
      get<BE_ServicioAeropuerto[]>(BE_GERSON, `/api/serviciosaeropuerto/aeropuerto/${cod}`),
  },
  lealtad: {
    listar:     ()                             => get<BE_ProgramaLealtad[]>(BE_GERSON, '/api/programalealtad'),
    registrar:  (m: Omit<BE_ProgramaLealtad, 'IdLealtad'>) =>
      post<{ IdGenerado: number }>(BE_GERSON, '/api/programalealtad', m),
    porPasajero:(id: number) => get<BE_ProgramaLealtad>(BE_GERSON, `/api/programalealtad/pasajero/${id}`),
    actualizar: (id: number, m: Partial<BE_ProgramaLealtad>) => put(BE_GERSON, `/api/programalealtad/${id}`, m),
  },
  quejas: {
    crear:      (m: Omit<BE_QuejaSugerencia, 'IdQueja'>) => post(BE_GERSON, '/api/quejassugerencias', m),
    porPasajero:(id: number) => get<BE_QuejaSugerencia[]>(BE_GERSON, `/api/quejassugerencias/pasajero/${id}`),
  },
  encuestas: {
    crear:      (m: Omit<BE_Encuesta, 'IdEncuesta'>) => post(BE_GERSON, '/api/encuestassatisfaccion', m),
    porVuelo:   (id: number) => get<BE_Encuesta[]>(BE_GERSON, `/api/encuestassatisfaccion/vuelo/${id}`),
  },
  atencionEspecial: {
    crear:      (m: Omit<BE_AtencionEspecial, 'IdAtencion'>) => post(BE_GERSON, '/api/atencionespecial', m),
    porPasajero:(id: number) => get<BE_AtencionEspecial[]>(BE_GERSON, `/api/atencionespecial/pasajero/${id}`),
  },
  historialReservas: {
    registrar:  (m: { IdReserva: number; CampoModificado: string; ValorAnterior: string; ValorNuevo: string; MotivoCambio?: string }) =>
      post(BE_GERSON, '/api/historialreservas', m),
  },

  // ── MODULOS BACKEND (:5089) — Módulos 15-20 ──────────────────────────────

  // Módulo 15
  empleados: {
    listar:     () => get<BE_Empleado[]>(BE_MODULOS, '/api/empleado'),
    obtener:    (id: number) => get<BE_Empleado>(BE_MODULOS, `/api/empleado/${id}`),
    crear:      (m: Omit<BE_Empleado, 'IdEmpleado'>) => post(BE_MODULOS, '/api/empleado', m),
    actualizar: (id: number, m: Partial<BE_Empleado>) => put(BE_MODULOS, `/api/empleado/${id}`, m),
  },
  departamentos: {
    listar:     () => get<BE_Departamento[]>(BE_MODULOS, '/api/departamento'),
    crear:      (m: Omit<BE_Departamento, 'IdDepartamento'>) => post(BE_MODULOS, '/api/departamento', m),
  },
  evaluaciones: {
    listar:     () => get<BE_Evaluacion[]>(BE_MODULOS, '/api/evaluaciondesempeno'),
    porEmpleado:(id: number) => get<BE_Evaluacion[]>(BE_MODULOS, `/api/evaluaciondesempeno/empleado/${id}`),
    crear:      (m: Omit<BE_Evaluacion, 'IdEvaluacion'>) => post(BE_MODULOS, '/api/evaluaciondesempeno', m),
  },
  vacaciones: {
    listar:     () => get<BE_VacacionPermiso[]>(BE_MODULOS, '/api/vacacionespermiso'),
    porEmpleado:(id: number) => get<BE_VacacionPermiso[]>(BE_MODULOS, `/api/vacacionespermiso/empleado/${id}`),
    crear:      (m: Omit<BE_VacacionPermiso, 'IdSolicitud'>) => post(BE_MODULOS, '/api/vacacionespermiso', m),
    aprobar:    (id: number, por: number) =>
      put(BE_MODULOS, `/api/vacacionespermiso/${id}/aprobar`, { AutorizadoPor: por }),
  },

  // Módulo 16
  ingresos: {
    listar:     () => get<BE_Ingreso[]>(BE_MODULOS, '/api/ingreso'),
    crear:      (m: Omit<BE_Ingreso, 'IdIngreso'>) => post(BE_MODULOS, '/api/ingreso', m),
  },
  gastos: {
    listar:     () => get<BE_Gasto[]>(BE_MODULOS, '/api/gasto'),
    crear:      (m: Omit<BE_Gasto, 'IdGasto'>) => post(BE_MODULOS, '/api/gasto', m),
  },
  proveedores: {
    listar:     () => get<BE_Proveedor[]>(BE_MODULOS, '/api/proveedor'),
    crear:      (m: Omit<BE_Proveedor, 'IdProveedor'>) => post(BE_MODULOS, '/api/proveedor', m),
  },
  tasas: {
    listar:     () => get<BE_TasaAeroportuaria[]>(BE_MODULOS, '/api/tasaaeropuertaria'),
    crear:      (m: Omit<BE_TasaAeroportuaria, 'IdTasa'>) => post(BE_MODULOS, '/api/tasaaeropuertaria', m),
  },
  cuentasBancarias: {
    listar:     () => get<BE_CuentaBancaria[]>(BE_MODULOS, '/api/cuentabancaria'),
    crear:      (m: Omit<BE_CuentaBancaria, 'IdCuenta'>) => post(BE_MODULOS, '/api/cuentabancaria', m),
  },
  movimientosBancarios: {
    listar:     () => get<BE_MovimientoBancario[]>(BE_MODULOS, '/api/movimientobancario'),
    crear:      (m: Omit<BE_MovimientoBancario, 'IdMovimiento'>) => post(BE_MODULOS, '/api/movimientobancario', m),
  },
  finanzas: {
    presupuestos:{ listar: () => get(BE_MODULOS, '/api/presupuesto'),
                   crear:  (m: any) => post(BE_MODULOS, '/api/presupuesto', m) },
  },

  // Módulo 18
  menores: {
    listar:     () => get<BE_MenorNoAcompanado[]>(BE_MODULOS, '/api/menoresnoacompanados'),
    obtener:    (id: number) => get<BE_MenorNoAcompanado>(BE_MODULOS, `/api/menoresnoacompanados/${id}`),
    crear:      (m: Omit<BE_MenorNoAcompanado, 'IdMenor'>) => post(BE_MODULOS, '/api/menoresnoacompanados', m),
    autorizaciones:{
      listar: () => get(BE_MODULOS, '/api/autorizacionmenor'),
      crear:  (m: any) => post(BE_MODULOS, '/api/autorizacionmenor', m),
    },
  },

  // Módulo 19
  carga: {
    envios: {
      listar:     () => get<BE_EnvioCarga[]>(BE_MODULOS, '/api/enviocarga'),
      obtener:    (id: number) => get<BE_EnvioCarga>(BE_MODULOS, `/api/enviocarga/${id}`),
      buscar:     (codigo: string) =>
        get<BE_EnvioCarga>(BE_MODULOS, `/api/enviocarga/codigo/${codigo}`),
      crear:      (m: Omit<BE_EnvioCarga, 'IdEnvio'>) => post(BE_MODULOS, '/api/enviocarga', m),
    },
    manifiestos: {
      listar:     () => get<BE_ManifiestoCarga[]>(BE_MODULOS, '/api/manifiestocarga'),
      porVuelo:   (id: number) => get<BE_ManifiestoCarga[]>(BE_MODULOS, `/api/manifiestocarga/vuelo/${id}`),
      crear:      (m: Omit<BE_ManifiestoCarga, 'IdManifiesto'>) => post(BE_MODULOS, '/api/manifiestocarga', m),
    },
    seguimiento: {
      porEnvio:   (id: number) => get<BE_SeguimientoCarga[]>(BE_MODULOS, `/api/seguimientocarga/envio/${id}`),
      crear:      (m: Omit<BE_SeguimientoCarga, 'IdSeguimiento'>) => post(BE_MODULOS, '/api/seguimientocarga', m),
    },
  },

  // Módulo 20
  mantenimiento: {
    ordenes: {
      listar:     () => get<BE_OrdenMantenimiento[]>(BE_MODULOS, '/api/ordenmantenimientopredictivo'),
      crear:      (m: Omit<BE_OrdenMantenimiento, 'IdOrdenMp'>) =>
        post(BE_MODULOS, '/api/ordenmantenimientopredictivo', m),
      actualizar: (id: number, m: Partial<BE_OrdenMantenimiento>) =>
        put(BE_MODULOS, `/api/ordenmantenimientopredictivo/${id}`, m),
    },
    alertasTecnicas: {
      listar:     () => get<BE_AlertaTecnica[]>(BE_MODULOS, '/api/alertastecnicas'),
      sinAtender: () => get<BE_AlertaTecnica[]>(BE_MODULOS, '/api/alertastecnicas/pendientes'),
      crear:      (m: Omit<BE_AlertaTecnica, 'IdAlertaTecnica'>) => post(BE_MODULOS, '/api/alertastecnicas', m),
    },
    checklists: {
      listar:     () => get(BE_MODULOS, '/api/checklistmantenimiento'),
      crear:      (m: any) => post(BE_MODULOS, '/api/checklistmantenimiento', m),
    },
    piezas: {
      listar:     () => get<BE_PiezaReemplazo[]>(BE_MODULOS, '/api/piezareemplazo'),
      stockBajo:  () => get<BE_PiezaReemplazo[]>(BE_MODULOS, '/api/piezareemplazo/stockbajo'),
      crear:      (m: Omit<BE_PiezaReemplazo, 'IdPieza'>) => post(BE_MODULOS, '/api/piezareemplazo', m),
    },
  },

  // Módulo 22
  combustible: {
    tanques: {
      listar:     () => get<BE_TanqueCombustible[]>(BE_MODULOS, '/api/tanquecombustible'),
      crear:      (m: Omit<BE_TanqueCombustible, 'IdTanque'>) => post(BE_MODULOS, '/api/tanquecombustible', m),
    },
    cargas: {
      listar:     () => get<BE_CargaCombustible[]>(BE_MODULOS, '/api/cargacombustible'),
      crear:      (m: Omit<BE_CargaCombustible, 'IdCargaCombustible'>) =>
        post(BE_MODULOS, '/api/cargacombustible', m),
    },
  },
};
